### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [0x44F/otax#2]
...

**Comment by gov-sec** [comment]
i receive OSError: [Errno 56] Socket is already connected 
instead so idk what to say

**Comment by gov-sec** [comment]
Packets sent from the client to the Gateway API are encapsulated within a gateway payload object and must have the proper opcode and data object set. The payload object can then be serialized in the format of choice (see ETF/JSON), and sent over the websocket. Payloads to the gateway are limited to a maximum of 4096 bytes sent, going over this will cause a connection termination with error code 4002.

Ok, what that's mean?
Every packet you sent to Gateway API needs to follow the request model.

{
  "op": 0,
  "d": {},
  "s": 42,
  "t": "GATEWAY_EVENT_NAME"
}
What is each object in this request model?
op: The code that tells the Gateway API what is your payload type. You can found the list of op here.

d: The payload itself. Here goes the json your are trying to send (your p variable)

s and t: Only required for op 0, so you can pass it as null for IDENTIFY.

What your request should looks like
{
    "op": 2,
    "d": {
        "token": "YOUR_TOKEN_HERE",
        "properties": {
            "$os": "linux",
            "$browser": "disco",
            "$device": "disco"
        }
    },
    "s": null,
    "t": null
}
